#!/usr/bin/env python3
"""
upload-nodemcu.py — Compile and upload the WiFi Leak Test sketch to NodeMCU boards.

Generates a config.h with station-specific settings at build time so the same
source sketch can be flashed to every station without manual edits.
"""
import os
import subprocess
import sys
import shutil
import argparse
import time
import signal
from pathlib import Path

# ======== Configuration ========
FQBN        = "esp8266:esp8266:nodemcuv2"
ARDUINO_CLI = "arduino-cli"
TMP_DIR     = "tmpArduino"
BASE_DIR    = Path(__file__).resolve().parent
SKETCH_SRC  = BASE_DIR / "arduino-codes" / "LeakTest_NodeMCU_BMP180.ino"

running_procs = []


# ======== Utility Functions ========

def run_cmd(cmd, cwd=None):
    """Run a command and stream output. Return True on success."""
    print(f"\n[CMD] {' '.join(cmd)}")
    proc = subprocess.Popen(
        cmd, cwd=cwd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True
    )
    running_procs.append(proc)
    for line in proc.stdout:
        print(line, end="")
    proc.wait()
    running_procs.remove(proc)
    return proc.returncode == 0


def prepare_sketch(ino_src, sketch_name, config_h_content):
    """
    Create a valid Arduino sketch folder, copy the .ino file into it,
    and write the generated config.h alongside it.
    """
    sketch_dir = os.path.join(TMP_DIR, sketch_name)
    ino_dest   = os.path.join(sketch_dir, f"{sketch_name}.ino")

    if os.path.exists(sketch_dir):
        shutil.rmtree(sketch_dir)

    os.makedirs(TMP_DIR, exist_ok=True)
    subprocess.run([ARDUINO_CLI, "sketch", "new", sketch_name], cwd=TMP_DIR, check=True)
    shutil.copyfile(ino_src, ino_dest)

    with open(os.path.join(sketch_dir, "config.h"), "w") as f:
        f.write(config_h_content)


def compile_and_upload(sketch_name, port, build_only=False):
    """Compile and optionally upload with automatic retry logic."""
    print(f"\n=== Processing {sketch_name.upper()} ===")

    output_dir = Path("binaries") / sketch_name
    if not run_cmd([
        ARDUINO_CLI, "compile",
        "--fqbn", FQBN,
        "--output-dir", str(output_dir),
        "--build-property", "compiler.cpp.extra_flags=-DUSE_CONFIG_H",
        sketch_name,
    ], cwd=TMP_DIR):
        print(f"❌ {sketch_name.upper()} compile failed.")
        sys.exit(1)

    if build_only:
        print(f"✅ {sketch_name.upper()} build-only done")
        return

    attempt = 1
    while True:
        print(f"🔁 Upload attempt {attempt} for {sketch_name.upper()}...")
        success = run_cmd([
            ARDUINO_CLI, "upload",
            "--fqbn", FQBN,
            "-p", port,
            "--input-dir", str(output_dir),
        ], cwd=TMP_DIR)
        if success:
            print(f"✅ {sketch_name.upper()} upload succeeded after {attempt} attempt(s)")
            break
        else:
            print(f"⚠️  Upload failed (attempt {attempt}). Retrying in 3 s...")
            attempt += 1
            time.sleep(3)


def build_config_h(station, ssids, passwords, ip, udp_port, interval):
    """Render the config.h content with station-specific values."""
    ssid_list = ", ".join(f'"{s}"' for s in ssids)
    pass_list = ", ".join(f'"{p}"' for p in passwords)
    return f"""\
// Auto-generated by upload-nodemcu.py — do not edit manually
#pragma once

#define STATION_ID       {station}
#define UDP_PORT         {udp_port}
#define DISPLAY_INTERVAL {interval}

static const char* const _ssids[]     = {{{ssid_list}}};
static const char* const _passwords[] = {{{pass_list}}};
static const int         WIFI_NO      = {len(ssids)};
static const char* const UDP_IP_STR   = "{ip}";
"""


def validate_ip(ip_str):
    parts = ip_str.split(".")
    if len(parts) != 4 or not all(p.isdigit() and 0 <= int(p) <= 255 for p in parts):
        raise argparse.ArgumentTypeError(f"Invalid IP address: {ip_str!r}")
    return ip_str


def handle_sigint(sig, frame):
    print("\n⚠️  Caught Ctrl+C, terminating running processes...")
    for proc in running_procs:
        try:
            proc.terminate()
        except Exception:
            pass
    sys.exit(1)


# ======== Main ========

def main():
    parser = argparse.ArgumentParser(
        description="Compile and upload the WiFi Leak Test sketch to a NodeMCU board"
    )
    parser.add_argument(
        "--station", required=True, type=int,
        help="Station number (0 = atmosphere reference, 1..N = RPC gap stations)"
    )
    parser.add_argument(
        "--ssids", required=True,
        help="Comma-separated WiFi SSIDs (e.g. 'net1,net2,net3')"
    )
    parser.add_argument(
        "--passwords", required=True,
        help="Comma-separated WiFi passwords (same order as --ssids)"
    )
    parser.add_argument(
        "--ip", required=True, type=validate_ip,
        help="Backend UDP server IP address"
    )
    parser.add_argument(
        "--udp-port", type=int, default=5006,
        help="UDP port (default: 5006)"
    )
    parser.add_argument(
        "--display-interval", type=int, default=3,
        help="Data transmission interval in seconds (default: 3)"
    )
    parser.add_argument(
        "--port", default="/dev/ttyUSB0",
        help="Serial port (default: /dev/ttyUSB0)"
    )
    parser.add_argument(
        "--build-only", action="store_true",
        help="Compile only, do not upload"
    )

    args = parser.parse_args()
    signal.signal(signal.SIGINT, handle_sigint)

    ssid_list = [s.strip() for s in args.ssids.split(",")]
    pass_list = [p.strip() for p in args.passwords.split(",")]

    if len(ssid_list) != len(pass_list):
        print("❌ Number of SSIDs and passwords must match.")
        sys.exit(1)

    sketch_name    = f"station-{args.station}"
    config_content = build_config_h(
        station=args.station,
        ssids=ssid_list,
        passwords=pass_list,
        ip=args.ip,
        udp_port=args.udp_port,
        interval=args.display_interval,
    )

    print(f"\n=== Building {sketch_name} ===")
    print(
        f"Station={args.station}, SSIDs={ssid_list}, "
        f"IP={args.ip}:{args.udp_port}, "
        f"Interval={args.display_interval}s, Port={args.port}"
    )

    prepare_sketch(SKETCH_SRC, sketch_name, config_content)
    compile_and_upload(sketch_name, args.port, args.build_only)

    print(f"\n🎉 Done: {sketch_name.upper()} complete!")


if __name__ == "__main__":
    main()
